{
 "title": "Spark",
 "tags": [ "spark" ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "number of online user",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "online_user_counter" }
   ]
  },
  {
   "title": "number of alive workers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "alive_worker_counter" }
   ]
  },
  {
   "title": "average response time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_time_summery_sum/ process_time_summery_count"
    }
   ]
  },
  {
   "title": "rate of increase success response",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(success_response_counter_total[1m])"
    }
   ]
  },
  {
   "title": "number of success response",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "success_response_counter_total" }
   ]
  },
  {
   "title": "number of fail response",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "fail_response_counter_total" }
   ]
  },
  {
   "title": "rate of increase fail response",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(fail_response_counter_total[1m])"
    }
   ]
  }
 ]
}