# Generated by Django 4.1.7 on 2023-06-29 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lab', '0007_data_status_alter_data_current_size_and_more'),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_percentage', models.FloatField()),
                ('think_time_in_second', models.IntegerField()),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.application')),
                ('data_files', models.ManyToManyField(to='lab.data')),
            ],
        ),
        migrations.CreateModel(
            name='ServerConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_counts', models.IntegerField()),
                ('spark_worker_counts', models.IntegerField()),
                ('cpu_of_every_worker', models.IntegerField()),
                ('memory_of_every_worker', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WorkloadConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users_count', models.IntegerField()),
                ('time_in_second', models.IntegerField()),
                ('apps', models.ManyToManyField(to='mixed_lab.appconfig')),
            ],
        ),
        migrations.CreateModel(
            name='MixedLab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config', models.TextField()),
                ('server_config', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mixed_lab.serverconfig')),
                ('workload_config', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mixed_lab.workloadconfig')),
            ],
        ),
    ]
