# Generated by Django 4.1.7 on 2023-03-01 15:35

from django.db import migrations, models
import lab.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.FileField(help_text='Your application must be a python file', upload_to=lab,
                                         verbose_name='Application file')),
                ('app_spark_workers_count',
                 models.CharField(max_length=1024, verbose_name='Application spark workers count')),
                ('work_load_users_count', models.CharField(max_length=1024, verbose_name='Work load users count')),
                ('work_load_data_sizes', models.CharField(max_length=1024, verbose_name='Work load data sizes')),
                ('work_load_end_time', models.DateTimeField()),
                ('work_load_user_duration', models.IntegerField()),
            ],
        ),
    ]
