# Generated by Django 4.1.7 on 2023-03-01 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='name',
            field=models.CharField(default=1, max_length=1024),
            preserve_default=False,
        ),
    ]
