# Generated by Django 4.1.7 on 2023-04-07 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0004_remove_lab_work_load_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='server_count',
            field=models.IntegerField(default=2, verbose_name='Servers count'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lab',
            name='worker_cpu_counts',
            field=models.IntegerField(default=2, verbose_name='Worker cpu counts'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lab',
            name='worker_memory_amount',
            field=models.CharField(default='10G', max_length=10, verbose_name='Worker memory amount'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lab',
            name='work_load_user_duration',
            field=models.CharField(max_length=1024, verbose_name='Work load users duration'),
        ),
    ]
