# Generated by Django 4.1.7 on 2023-05-18 11:19

import django.core.validators
from django.db import migrations, models
import lab.models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0005_lab_server_count_lab_worker_cpu_counts_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_data', models.FileField(help_text='Your sample data must be a csv file', upload_to=lab.models.get_data_file_path, validators=[django.core.validators.FileExtensionValidator(['csv'])], verbose_name='Sample data file')),
                ('desired_size', models.CharField(help_text='Your desired size with postfix: [kb, mb, gi] for example `100 mb`', max_length=7, validators=[lab.models.validate_data_size], verbose_name='Desired Size')),
                ('current_size', models.CharField(max_length=7, verbose_name='Current Size')),
            ],
        ),
    ]
