# Generated by Django 4.1.7 on 2023-05-18 13:00

import django.core.files.storage
import django.core.validators
from django.db import migrations, models
import lab.models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0006_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='status',
            field=models.CharField(choices=[('Raw', 'Raw'), ('Generated', 'Generated'), ('Pending', 'Pending')], default='Raw', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='data',
            name='current_size',
            field=models.CharField(blank=True, max_length=7, verbose_name='Current Size'),
        ),
        migrations.AlterField(
            model_name='data',
            name='sample_data',
            field=models.FileField(help_text='Your sample data must be a csv file', storage=django.core.files.storage.FileSystemStorage(location='/mnt/data'), upload_to=lab.models.get_data_file_path, validators=[django.core.validators.FileExtensionValidator(['csv'])], verbose_name='Sample data file'),
        ),
    ]
