# Generated by Django 4.1.7 on 2023-07-04 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0002_remove_application_name'),
        ('lab', '0007_data_status_alter_data_current_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.application',
                                    verbose_name='Application'),
        ),
    ]
