# Generated by Django 4.1.7 on 2023-07-05 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0009_lab_total_time_of_experiment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='app_spark_workers_count',
            field=models.CharField(help_text='<h4>Field spark worker count must be in format <number>,<number>,... like 1,5,2,7 This means that initially the number of spark workers is 1, but later on, it increases to five, and ...</h4>', max_length=1024, verbose_name='Application spark workers count'),
        ),
        migrations.AlterField(
            model_name='lab',
            name='server_count',
            field=models.IntegerField(choices=[(1, 1), (2, 2)], help_text='<h4>server count must be 1 or 2</h4>', verbose_name='Servers count'),
        ),
        migrations.AlterField(
            model_name='lab',
            name='total_time_of_experiment',
            field=models.IntegerField(help_text='<h4>Field workload user think time must be in format <seconds>,<seconds>,... like 3200 It represents the elapsed time between the beginning and end of the experimental process.</h4>', verbose_name='Total time of experiment'),
        ),
        migrations.AlterField(
            model_name='lab',
            name='work_load_data_sizes',
            field=models.CharField(blank=True, help_text='<h4>Field workload data sizes must be in format <data_file_name>,<data_file_name>,...  This means size of data processed, which should be in CSV format accompany with its name like like mlp_8KB.csv or feature_selection_100MB.csv</h4>', max_length=1024, null=True, verbose_name='Work load data sizes'),
        ),
        migrations.AlterField(
            model_name='lab',
            name='work_load_user_duration',
            field=models.CharField(help_text='<h4>Field workload user duration must be in format <seconds>,<seconds>,... like 300,500,300,700 This means that initially number of seconds that users is using your application is 300, but later on, it increase to five hundred. ...</h4>', max_length=1024, verbose_name='Work load users duration'),
        ),
        migrations.AlterField(
            model_name='lab',
            name='work_load_user_think_time',
            field=models.CharField(help_text='<h4>Field workload user think time must be in format <seconds>,<seconds>,... like 30,50This means after a request is processed by the system, the corresponding client will wait for some time before sending the next request</h4>', max_length=1024, verbose_name='Work load users think time'),
        ),
        migrations.AlterField(
            model_name='lab',
            name='work_load_users_count',
            field=models.CharField(help_text='<h4>Field workload users count must be in format <number>,<number>,... like 10,5,8,12 This means that initially the number of users is 10 but later on, it increases to five. ...</h4>', max_length=1024, verbose_name='Work load users count'),
        ),
        migrations.AlterField(
            model_name='lab',
            name='worker_cpu_counts',
            field=models.IntegerField(help_text='<h4>Field cpu must be a number like (1 or 2 or 3 or ....)</h4>', verbose_name='Worker cpu counts'),
        ),
        migrations.AlterField(
            model_name='lab',
            name='worker_memory_amount',
            field=models.CharField(help_text='<h4>Field memory must be in format <number>g like (10g or 2g or 12g)</h4>', max_length=10, verbose_name='Worker memory amount'),
        ),
    ]
