FROM bde2020/spark-worker:3.3.0-hadoop3.3

COPY ./requirements.txt .
RUN apk update
RUN apk add make automake gcc g++ subversion python3-dev
RUN /usr/bin/python3.7 -m pip install --upgrade pip
RUN pip3 install numpy==1.20.0

CMD ["/bin/bash", "/worker.sh"]
